Traceback (most recent call last):
  File "C:\Users\Epsilon_Luoo\miniconda3\envs\p2s\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Epsilon_Luoo\miniconda3\envs\p2s\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Epsilon_Luoo\miniconda3\envs\p2s\Lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Epsilon_Luoo\miniconda3\envs\p2s\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Epsilon_Luoo\miniconda3\envs\p2s\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Epsilon_Luoo\miniconda3\envs\p2s\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Epsilon_Luoo\miniconda3\envs\p2s\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# 语法错误（在编译时出错，Python 并没有开始运行代码）
print("哦不！) # Error! 缺少结尾引号
------------------


[1;36m  Cell [1;32mIn[17], line 2[1;36m[0m
[1;33m    print("哦不！) # Error! 缺少结尾引号[0m
[1;37m          ^[0m
[1;31mSyntaxError[0m[1;31m:[0m unterminated string literal (detected at line 2)


